version: '3.1'

services:

  db:
    image: postgres
    ports:
      - 5432:5432/tcp
    volumes:
      - "./data:/var/lib/postgresql/data"
    restart: always
    environment:
      POSTGRES_USER: ascold
      POSTGRES_PASSWORD: ascold
      POSTGRES_DB: todos